name: Unity CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build for Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('**/Assets/**', '**/ProjectSettings/**') }}

      - name: Install Unity
        uses: game-ci/unity-installer@v2
        with:
          version: 2022.3.10f1

      - name: Activate Unity
        uses: game-ci/unity-activate@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Build
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: StandaloneWindows64
